version: '3.8'

services:

  application:
    image:
      loudbar/string-shrink
    build:
      dockerfile:
        Dockerfile
      context: .
    container_name: application
    networks:
      - cloud
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    image:
      loudbar/string-shrink_db
    build:
      dockerfile:
        Dockerfile
      context: ./Redis
    container_name: redis
    networks:
      - cloud
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  redis-volume:
    external: true

networks:
  cloud:
    external: true
